### ISSUE TITLE
地名

### ISSUE THREAD

**Issue by thothit** [a-thok/rime-hokkien#2]
「雲霄」愛讀做ûn-sio
「龍岩」愛讀做lîng-nâ
猶有：

> 潮洲 tio tsiu
>   ...
>   潮洲話 tio ciu uee

應該是「潮州」「潮州話」

**Comment by a-thok** [comment]
「雲霄」兮讀音我是「糾結」誠久囉。
我若是剔hun5，就有儂糾正我，是un5則著。等我改做un5，又閣有儂糾正我，講是著讀做hun5。作為泉州儂，這个地名到底按怎讀我真正袂曉得…
佇有閣較充足兮證據之前，我決定這个音先維持現狀，毋去改伊。

「龍岩」，我文件內面無標音，袂記得是為啥物囉。
大部份無標音兮詞，是為著兼容腔口，可能我是想著漳州凡勢是讀liong5-na5，則無共讀音定死。但是「岩」我無設單字音na5，致使ling5-na5拍袂出這个詞。
借問友兮，汝敢知漳州有區分ing/eng佮iong兮所在，「龍岩」兮「龍」是讀liong5抑是ling5？

「潮州」是我無斟酌寫賺字去，歹勢。

**Comment by thothit** [comment]
其實我平常時嘛真無閒，若毋是做風颱放假， 我嘛無通現看著汝兮回覆。
做為雲霄儂，阮肯定會讀un5-sio。隔壁縣嘛攏是讀做un5-sio。若泉州兮朋友有其他讀法，建議刪去標音。
其實「龍岩」，若是漳南會讀liong5-na5較濟，漳北會讀ling5-na5較濟（嘛有儂讀做liong5-na5）。按呢應該著添加na5這个音（反正讀giam5毋著）。
另外 ing/eng/iong這組關係會較複雜。漳北兮ing，對應漳南兮eng，但是嘛有所在讀iong兮。ik韻，漳南會讀做ek，雲霄漳浦等所在猶有iok兮音。
其實iong，臺灣嘛分無偌清楚。比如講「龍」字，臺灣讀liong5/ling5。
猶有

> ```
> - derive/^([ptkblghcjs])?e(\d)$/$1ei$2/       #漳南
> ```

建議改做

> ```
> - derive/^([ptkblghcjs]s?h?)?e(\d)$/$1ei$2/       #漳南
> ```

 來處理送氣音。 猶會使添上對ek、iok兮支援：

> ```
> - derive/ik/ek/   #漳南
> - derive/ik/iok/  #漳南
> ```

順紲，建議「遍」字添上pian3兮音（廈門、漳州攏有pian3兮音），「區」字添上khi1音（漳州腔）。

**Comment by a-thok** [comment]
我有一个同事是漳浦兮，彼日我刁工問伊，看「雲霄」怹是按怎讀。伊共我講是讀hun5-sio1…
但既然兄汝是雲霄儂，這个地名當然著照恁在地儂兮習慣來讀。讀音我已經改過來。

另外，汝下底所建議這兩條我也有對應兮修正。
我家己有小可測試，毋過對漳州腔口畢竟毋是100%了解，毋知會閣有啥物錯誤袂。
若有，則請另外提出。這條issue我共伊關捒囉。
