### ISSUE TITLE
一寡通參考的輸入法表 (.cin)

### ISSUE THREAD

**Issue by Yoxem** [a-thok/rime-hokkien#8]
因為漢字佮詞庫足濟，而且各家用字無kâng，建議增加、整合一寡輸入法表的用字，以提供需求。
以下是通參考的表，共調號轉做數字，用若 perl 的 `perl -pe s/^(\S+)\s+(\S+)$/$2     $1/g` 應該就通轉做 rime 的表，閣提這个粗批來修改拼法等等就應該會使。

1.  GPL 授權
1.1. 灣娘台灣閩南語漢字輸入法 0.0.23（如附檔 [uanniu.cin.zip](https://github.com/a-thok/rime-hokkien/files/1277955/uanniu.cin.zip)）
1.2. poj-holo.cin.zip（如附檔 [poj-holo.cin.zip](https://github.com/a-thok/rime-hokkien/files/1277956/poj-holo.cin.zip)。來自廈門音新字典，字 khah 濟，但是用字有可能無統一，建議參考 http://taigi.fhl.net/dick 確認，頭字大寫的是文言音，其他兮是借音抑是白話音等）
2. 公共領域，通自由使用
2.1 臺語TRS輸入法（https://github.com/a-tsioh/TRS.cin/blob/master/result.cin ，by 阿石，有詞組，應該是教育部用字，但是愛整理）
3. 免費授權
3.1 教育部台閩漢字 https://github.com/chinese-opendesktop/cin-tables/blob/master/tbhs.cin （有詞組，待整理）
注意：授權寫「使用者可以免費下載、使用、重製、散布本安裝套件，惟重製和散布時，必須保持本安裝套件完整。」
3. 授權待查
3.1 TLPA 台語：https://github.com/chinese-opendesktop/cin-tables/blob/master/tlpa.cin
3.2 台語注音輸入法（吳守禮等，需要將代碼用 regexp 轉為台羅，再人工修正部份標音）：https://github.com/chinese-opendesktop/cin-tables/blob/master/tin.cin
3.3台式閩南語注音（楊青矗，需要將代碼用 regexp 轉為台羅，再人工修正部份標音）： https://github.com/chinese-opendesktop/cin-tables/blob/master/taiwan-minnan-zhuyin.cin
3.4 臺語注音輸入法（張耒等，需要將代碼用 regexp 轉為台羅，再人工修正部份標音）https://github.com/chinese-opendesktop/cin-tables/blob/master/taiwanese.cin
4. 附註：其他的表格可以參考：https://github.com/chinese-opendesktop/cin-tables/
以上提供參考。

**Comment by a-thok** [comment]
這个輸入法詞庫兮初衷之一，是欲起到正字兮作用。佇咧製作兮過程中，就一直共規範、共統一用字這項代誌考慮在內。
我個人無任何權威性，所以佇咧選字兮時陣，除了個別字有依照我所接觸兮閩南語文社區兮實際情況來調整，大大多數兮字，我攏是遵照臺灣教育部兮寫法。

各種寫法已經真濟，佇我這个詞庫內面，我想欲做兮，毋是混用無數兮寫法、更加毋是加添新兮寫法。我想欲做兮，是鼓勵使用者共規範囥佇個人偏好、乃至學術觀點兮頭前。規範第一重要，咱共同來遵守一套規範兮寫法，我認為按呢對閩南語文兮發展較有利。
目前，佇閩南語文兮規範性面頂，無任何兮機構、部門抑是組織，比臺灣教育部閣較權威。所以我基本以臺灣教育部兮寫法為準。

若是對具體兮用字有爭議，會使單獨討論，若是有理，會使改字。甚至，閣較好是直接向教育部反饋（我個人捌向怹反饋著）。
至於整合各種寫法，因為違背這个詞庫一起頭兮用意，違背我製作這个詞庫時兮初衷，所以無佇我兮考慮範圍內。真歹勢。
